project:
  title: "ICIP-2023"
  output-dir: docs

format:
  html:
    theme: lux

markdown:
  flavor: gfm

# editor:
#   markdown:
#     wrap: 72
#     references: 
#       location: block
#     canonical: true
#     flavor: gfm
